In [1]:
import pandas as pd

from scipy import stats

In [ ]:
# 11.  What can be concluded from the output if the printed p-value is 0.0002?  


batch_A = [82,85,90,88,86]
batch_B = [78,76,80,79,77]
batch_c = [91,89,92,94,90]

f_stat,p_value = stats.f_oneway(batch_A,batch_B,batch_c)
print(p_value)

# p-value is less than 0.05, 
# we can reject the null hypothesis a
# and conclude that there is a significant difference in the mean scores of the three batches.

3.2655384154397063e-06


In [8]:
import pandas as pd
import numpy as np

data = np.array([5,15,25,35,45])
scaled_data = (data - np.mean(data)) / np.max(data - np.mean(data))
print(scaled_data)

[-1.  -0.5  0.   0.5  1. ]


In [11]:
arr2d = np.array([[11,12,13,14],
                  [21,22,23,24],
                  [31,32,33,34],
                  [41,42,43,44]])
print(arr2d[1:3,1:],arr2d[::-1,0],
      arr2d[:2, ::-1])            

[[22 23 24]
 [32 33 34]] [41 31 21 11] [[14 13 12 11]
 [24 23 22 21]]


In [13]:
senetence = "Data Sciene is powerfull"
words = senetence.split()
result = ''
for word in words:
    if len(word)%2 == 0:
        result += word[::-2] + ' '
    else:
        result += word[::2] + ' '
print(result.strip())

aa eec s pwrul


In [17]:
word = "understanding"
output = ''

for i in range(1,len(word),2):
    if word[i] not in ['a','e','i','o','u']:
        output += word[i]
print(output)

nsdn


In [18]:
x = [10,20,30,40,50,60,70]
y = slice(1,-1,2)
print(x[y])


[20, 40, 60]
